version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: monthly
      time: "16:20"
      timezone: Europe/Oslo

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "16:20"
      timezone: Europe/Oslo
