package com.example.controller;

import io.micronaut.gcp.function.http.HttpFunction;
import io.micronaut.http.HttpMethod;
import io.micronaut.http.HttpStatus;
import io.micronaut.test.extensions.junit5.annotation.MicronautTest;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

/**
 * Controller tests generated by Micronaut launch
 */
@MicronautTest
public class DemoControllerHttpFunctionTests {

    @Test
    public void testGet() throws Exception {
        try (HttpFunction function = new HttpFunction()) {

            // act
            var response = function.invoke(HttpMethod.GET, "/pubsubEmulatorDemo");

            // assert
            assertEquals(HttpStatus.OK, response.getStatus());
        }
    }
}
